### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by slackwarelinux** [mattcasters/kettle-neo4j-core#3]
Downloading from eclipse-maven-repo: https://mvnrepository.com/org/pentaho/pentaho-ce-jar-parent-pom/8.1-SNAPSHOT/maven-metadata.xml
Downloading from eclipse-maven-repo: https://mvnrepository.com/org/pentaho/pentaho-ce-jar-parent-pom/8.1-SNAPSHOT/pentaho-ce-jar-parent-pom-8.1-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for kettle-neo4j:kettle-neo4j-core:1.0.1: Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:8.1-SNAPSHOT in eclipse-maven-repo (https://mvnrepository.com) and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project kettle-neo4j:kettle-neo4j-core:1.0.1 (/data/workspace/Github/kettle-neo4j-core/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for kettle-neo4j:kettle-neo4j-core:1.0.1: Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:8.1-SNAPSHOT in eclipse-maven-repo (https://mvnrepository.com) and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by mattcasters** [comment]
The Pentaho dependencies come unfortunately from a Pentaho Maven server.
Throw this in ~/.m2 :  https://github.com/pentaho/maven-parent-poms/blob/master/maven-support-files/settings.xml

**Comment by slackwarelinux** [comment]
thanks
